version: '3.8'

services:
  bot:
    build: .
    container_name: kilovatt_market_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # Для сохранения базы данных
    env_file:
      - .env  # Файл с переменными окружения
    environment:
      - TZ=Europe/Moscow  # Часовой пояс